typedef short nsEveLocationTypeValue;

[scriptable, uuid(4cc443f1-538e-4a0d-be4d-bde2df2e6866)]
interface nsEveLocationType {
    const nsEveLocationTypeValue LOCATION_OFFICE = 1;
    const nsEveLocationTypeValue LOCATION_HANGAR = 2;
    const nsEveLocationTypeValue LOCATION_SYSTEM = 3;
};

typedef long nsEveItemTypeIDValue;

[scriptable, uuid(d1c2edf3-635c-460b-b020-b386841c528d)]
interface nsEveItemTypeID {
    const nsEveItemTypeIDValue TYPE_OFFICE = 27;
};

typedef long nsEveItemGroupIDValue;

[scriptable, uuid(8ff27734-8386-4c2d-a363-753eb98ad912)]
interface nsEveItemGroupID {
    const nsEveItemGroupIDValue GROUP_CONTROL_TOWER = 365;
};

typedef long nsEveItemCategoryIDValue;

[scriptable, uuid(bbc8cd63-8c66-4a67-9840-e62f1dac7a51)]
interface nsEveCategoryID {
    const nsEveItemCategoryIDValue CATEGORY_STRUCTURE = 23;
    const nsEveItemCategoryIDValue CATEGORY_SKILL     = 16;
};

typedef short nsEveAuthTokenTypeValue;

[scriptable, uuid(708f6d64-babc-4b11-9d80-1a41815739b9)]
interface nsEveAuthTokenType {
    const nsEveAuthTokenTypeValue TYPE_NOCHAR   = 0; /* no character ID supplied */
    const nsEveAuthTokenTypeValue TYPE_LIMITED  = 1;
    const nsEveAuthTokenTypeValue TYPE_FULL     = 2;
    const nsEveAuthTokenTypeValue TYPE_DIRECTOR = 2; /* used for corp data */
};

typedef short nsEveTransactionTypeValue;

[scriptable, uuid(e368756f-9bd1-481b-af73-70414ccd107d)]
interface nsEveTransactionType {
    const nsEveTransactionTypeValue TYPE_SELL   = 0;
    const nsEveTransactionTypeValue TYPE_BUY    = 1;
};

typedef short nsEveTransactionForValue;

[scriptable, uuid(09a63fac-8e15-4cae-b221-7b14d0f4a282)]
interface nsEveTransactionFor {
    const nsEveTransactionForValue TYPE_PERSONAL    = 0;
    const nsEveTransactionForValue TYPE_CORPORATION = 1;
};

