#include "nsISupports.idl"
#include "EveConstants.idl"
#include "nsIEveHRManager.idl"

[scriptable, uuid(07504627-1766-49a0-b2c8-fbf0e9a406b7)]
interface nsIEveApiRequester : nsISupports {
    void refreshData(in string type, in nsISupports data);
};

[scriptable, uuid(87f3fe9b-6638-40da-b69f-e60163667b4a)]
interface nsIEveAuthToken : nsISupports {
    readonly attribute long accountID;
    readonly attribute string apiKey;
    readonly attribute nsEveAuthTokenTypeValue type;
    attribute long characterID;
};

[scriptable, uuid(a9e7ed2f-db32-475b-ac54-2006caa4b924)]
interface nsIEveAuthManager : nsISupports {
    void getTokenForAccount(in long accountID,
            in nsEveAuthTokenTypeValue type,
            [retval] out nsIEveAuthToken retv);
    void getTokenForChar(in nsIEveCharacter character,
            in nsEveAuthTokenTypeValue type,
            [retval] out nsIEveAuthToken retv);
    void getTokenForCorp(in nsIEveCorporation corporation,
            in nsEveAuthTokenTypeValue type,
            [retval] out nsIEveAuthToken retv);
};

