#include "nsISupports.idl"
#include "nsIEveInventoryService.idl"
#include "EveConstants.idl"
#include "nsIEveControlTower.idl"

interface nsIEveCorporation;
interface nsIEveAuthToken;
interface nsEveAuthTokenType;
[scriptable, uuid(b8922ed5-966c-4a92-b0d7-e89391b56cf3)]
interface nsIEveCharacter : nsISupports {
    readonly attribute long id;
    readonly attribute long account;
    readonly attribute nsIEveCorporation corporation;
    readonly attribute string name;
    void getAssets(out unsigned long count,
            [array, size_is(count), retval] out nsIEveItem retv);
    void getAuthToken(in nsEveAuthTokenTypeValue type,
            [retval] out nsIEveAuthToken retv);
};

[scriptable, uuid(2cedf6f4-2590-4291-92cc-51cc8b128cd6)]
interface nsIEveCorporation : nsISupports {
    readonly attribute long id;
    readonly attribute string name;
    void getMembers(out unsigned long count,
            [array, size_is(count), retval] out nsIEveCharacter retv);
    void getAssets(out unsigned long count,
            [array, size_is(count), retval] out nsIEveItem retv);
    void getControlTowers(out unsigned long count,
            [array, size_is(count), retval] out nsIEveControlTower retv);
    void getAuthToken(in nsEveAuthTokenTypeValue type,
            [retval] out nsIEveAuthToken retv);
};

[scriptable, uuid(761e9733-364b-460e-8e3a-eb1d28fb5cd3)]
interface nsIEveHRManager : nsISupports {
    void getAllCorporations(out unsigned long count,
            [array, size_is(count), retval] out nsIEveCorporation retv);
    void getCorporation(in long corpID, [retval] out nsIEveCorporation retv);
    void getCharacter(in long charID, [retval] out nsIEveCharacter retv);
};

